name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide clear repro steps.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Exact steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output (redact secrets)
  - type: input
    id: version
    attributes:
      label: Diablo version / commit
      placeholder: v0.1.0 or commit SHA
